In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is availabler")
  print(f"Device name{torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available")

GPU is availabler
Device nameTesla T4


# Creating tensor

In [4]:
a= torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3) #for random value

tensor([[0.1688, 0.3675, 0.3845],
        [0.3518, 0.6575, 0.5351]])

In [9]:
torch.manual_seed(100) # same number generate hbe
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor( [ [1,2,3],[4,5,6] ] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
torch.arange(0,10,2) # start from 0, end 10, gap 2

tensor([0, 2, 4, 6, 8])

In [13]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# tensors shape

In [14]:
x= torch.tensor( [ [1,2,3],[4,5,6] ] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[        0, 714272416,         0],
        [        0,         1,         6]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data Type

In [20]:
x.dtype

torch.int64

In [21]:
torch.tensor( [1.0,2.0,3.0,4.0], dtype= torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [22]:
torch.tensor( [1.0,2.0,3.0,4.0], dtype= torch.float32)

tensor([1., 2., 3., 4.])

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [24]:
x.dtype

torch.int64

# Mathematical operation

In [25]:
x= torch.tensor( [ [1,2,3],[4,5,6] ] )

In [26]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [28]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [30]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [31]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [32]:
#floor

x = x*100
x

tensor([[100, 200, 300],
        [400, 500, 600]])

In [33]:
x// 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [34]:
x** 2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [35]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element wise operation

In [36]:
import torch

a = torch.rand(2,3)
b = torch.rand(2,3)

In [37]:
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [38]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [39]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [40]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [41]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [42]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [43]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [44]:
b**a

tensor([[0.3447, 0.3898, 0.4863],
        [0.8397, 0.5568, 0.9826]])

In [45]:
c= torch.tensor([-1,-2,-3,-4])

In [46]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [47]:
torch.neg(c) # double neg + hbe

tensor([1, 2, 3, 4])

In [48]:
#Round convert

import torch

d = torch.tensor([1.3, 24.5, 3.67, 4])

torch.round(d)

tensor([ 1., 24.,  4.,  4.])

In [49]:
torch.ceil(d)

tensor([ 2., 25.,  4.,  4.])

In [50]:
torch.floor(d)

tensor([ 1., 24.,  3.,  4.])

In [51]:
torch.clamp(d, min=1, max=2)

tensor([1.3000, 2.0000, 2.0000, 2.0000])

# Reduction operation

In [52]:
e= torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)

In [53]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [54]:
torch.sum(e)

tensor(27.)

In [55]:
torch.sum(e, dim=0) # dimantion wise

tensor([9., 9., 9.])

In [56]:
torch.sum(e, dim=1)

tensor([10., 17.])

In [57]:
torch.mean(e)

tensor(4.5000)

In [58]:
torch.mean(e, dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [59]:
torch.median(e)

tensor(1.)

In [60]:
torch.max(e)

tensor(9.)

In [61]:
torch.min(e)

tensor(0.)

In [62]:
torch.prod(e)

tensor(0.)

In [63]:
torch.std(e)

tensor(4.5935)

In [64]:

torch.var(e)

tensor(21.1000)

In [65]:
#arg max, argmin

torch.argmax(e)

tensor(2)

In [66]:
torch.argmin(e)

tensor(0)

# Special function

In [67]:
k= torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [68]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [69]:
#Exponential

torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [70]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [71]:
#sigmoid function
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [75]:
import torch

k = torch.tensor([1,2,3])

torch.softmax(k.float(), dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [76]:
torch.relu(k)

tensor([1, 2, 3])

# Inplace operation

In [77]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [82]:
b= a+5
b

tensor([6, 7, 8])

In [83]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [84]:
m, n

(tensor([[0.5277, 0.2472, 0.7909],
         [0.4235, 0.0169, 0.2209]]),
 tensor([[0.9535, 0.7064, 0.1629],
         [0.8902, 0.5163, 0.0359]]))

In [85]:
m.add_(n)

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [86]:
torch.relu_(m)

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [87]:
m.relu_()

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

# Copying a tensor

In [97]:
a=torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [98]:
b=a

In [99]:
b

tensor([1, 2, 3, 4, 5])

In [100]:
b[2]=30

In [101]:
b

tensor([ 1,  2, 30,  4,  5])

In [102]:
a

tensor([ 1,  2, 30,  4,  5])

In [103]:
b= a.clone()

In [104]:
b

tensor([ 1,  2, 30,  4,  5])