# Version 1

In [33]:
import torch
import torch.nn as nn

In [34]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear(features)
#     out = self.sigmoid(out)

#     return out

# Version 2

In [35]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

# Version 3

In [36]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [37]:
# Create dataset

features = torch.rand(10,5)

In [38]:
features

tensor([[0.4475, 0.4348, 0.0551, 0.3529, 0.8894],
        [0.5961, 0.3165, 0.5027, 0.1551, 0.5302],
        [0.7129, 0.4635, 0.9073, 0.7525, 0.9715],
        [0.3941, 0.6118, 0.8830, 0.5010, 0.3420],
        [0.8845, 0.8536, 0.8198, 0.0591, 0.0363],
        [0.8623, 0.7909, 0.3890, 0.8611, 0.9297],
        [0.9143, 0.7473, 0.3114, 0.0525, 0.7430],
        [0.5075, 0.9339, 0.6992, 0.2368, 0.3531],
        [0.6510, 0.1132, 0.3656, 0.7671, 0.1152],
        [0.6000, 0.8694, 0.1552, 0.8554, 0.5656]])

In [39]:
features.shape[1]

5

In [40]:
#create model

model = Model(features.shape[1])

In [41]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.6215],
        [0.6122],
        [0.6047],
        [0.5987],
        [0.5843],
        [0.6135],
        [0.6140],
        [0.5922],
        [0.6047],
        [0.6019]], grad_fn=<SigmoidBackward0>)

In [46]:
#show model weights

#model.linear1.weight => for version 1 and 2

model.network[0].weight #for version 3
#model.network[1].weight
model.network[2].weight
#model.network[3].weight

Parameter containing:
tensor([[-0.1171,  0.1361,  0.2050]], requires_grad=True)

In [32]:
# visualize

!pip install torchinfo

In [43]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00