In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter #Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize  #Splits text into individual words/tokens.
import nltk # Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [3]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [4]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

# Tokenize

In [5]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build vocabs

In [6]:
#build vocab
vocab = { '<unk>' : 0 }

In [7]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]= len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [8]:
len(vocab)

284

# Extract sentence from data

In [9]:
input_sentences = document.split('\n')

In [10]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [11]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [12]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [13]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# training Sequence form

In [14]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [15]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [16]:
len(training_sequence)

555

In [17]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [18]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [19]:
max(len_list)

25

In [20]:
#logic
[0]* (max(len_list)-len(sequence))

[]

In [21]:
training_sequence[0]

[1, 2]

In [22]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append( [0]* (max(len_list)-len(sequence)) + sequence  )


In [23]:
len(padded_training_sequence[0])

25

In [24]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [25]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

# tensor convert

In [26]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [27]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [28]:
X = padded_training_sequence[:, :-1]

In [29]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [30]:
y = padded_training_sequence[:,-1]

In [31]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [32]:
len(X)

555

In [33]:
len(y)

555

# Custom Dataset and Dataloader

In [34]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx) :
    return self.X[idx], self.y[idx]

In [35]:
dataset = CustomDataset(X,y)

In [36]:
len(dataset)

555

In [37]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [38]:
for input , output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          62,   1,   3,  10,  63,  64,  65,  66,  67,  68],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0, 239, 254,  10, 153, 255,  11,   6, 256, 257],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   1, 214, 215],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 136, 250,  85,   8, 251,  51,  42,  98],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
           1,   4, 170,  10, 153, 171, 172, 173, 120, 174],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 239, 254,  10, 153, 255,  11,   6, 256],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   5,   6,
           7,   8,   9,  10,  11,  12,  13,   1,  14,  15],
        [  0,   0,   0,   0

In [39]:
X.shape

torch.Size([555, 24])

In [40]:
y.shape

torch.Size([555])

In [41]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [42]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [48]:
# X[555]

IndexError: index 555 is out of bounds for dimension 0 with size 555

In [44]:
len(dataset)

555

In [45]:
len(vocab)

284

In [46]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)


  def forward():
    pass

# LSTM Cell

In [47]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [49]:
model = LSTMModel(len(vocab))

In [50]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [51]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [52]:
len(vocab)

284

In [53]:
x = nn.Embedding(284,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150, 284)

In [54]:
len(dataset)

555

In [55]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [56]:
dataset[0][0].shape

torch.Size([24])

In [57]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [58]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [59]:
x(a)

tensor([[[ 0.2634, -0.2372, -0.6940,  ..., -0.7760,  0.5299, -0.3423],
         [ 0.2634, -0.2372, -0.6940,  ..., -0.7760,  0.5299, -0.3423],
         [ 0.2634, -0.2372, -0.6940,  ..., -0.7760,  0.5299, -0.3423],
         ...,
         [ 0.2634, -0.2372, -0.6940,  ..., -0.7760,  0.5299, -0.3423],
         [ 0.2634, -0.2372, -0.6940,  ..., -0.7760,  0.5299, -0.3423],
         [-0.4837, -0.3638, -1.0758,  ..., -0.5427,  0.4582, -0.5488]]],
       grad_fn=<EmbeddingBackward0>)

In [60]:
x(a).shape

torch.Size([1, 24, 100])

In [61]:
b = x(a)

In [62]:
y(b)

(tensor([[[ 0.0713,  0.1072, -0.0898,  ..., -0.0374,  0.2519, -0.0673],
          [ 0.1520,  0.1427, -0.1403,  ..., -0.0586,  0.3310, -0.1142],
          [ 0.2068,  0.1527, -0.1726,  ..., -0.0694,  0.3585, -0.1414],
          ...,
          [ 0.2795,  0.1519, -0.2376,  ..., -0.0768,  0.3770, -0.1715],
          [ 0.2795,  0.1519, -0.2376,  ..., -0.0768,  0.3770, -0.1715],
          [ 0.1929, -0.0004, -0.3022,  ..., -0.2915,  0.3796, -0.3258]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[ 1.9292e-01, -4.3955e-04, -3.0222e-01, -2.3944e-01,  2.3342e-01,
             4.1313e-02, -1.0157e-01,  2.3517e-02,  1.5441e-01,  9.0775e-02,
             1.4543e-01, -2.8699e-01, -6.8007e-02,  7.1919e-03,  5.5407e-02,
            -1.5294e-02,  9.0362e-02, -2.3254e-01, -1.2235e-01,  5.8682e-02,
             1.9422e-01,  3.4974e-02,  2.9727e-01,  3.2289e-01, -4.6060e-03,
            -2.4447e-01, -3.1780e-01, -1.5550e-01, -1.9145e-02,  2.9630e-02,
             1.7294e-01,  2.7273e-01,  1.6566e-01,

In [63]:
len(y(b))

2

In [64]:
c ,d = y(b)

In [65]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

In [66]:
len(y(b))

2

In [67]:
len(d)

2

In [68]:
e, f = d


In [69]:
e.shape  #Cell state

torch.Size([1, 1, 150])

In [70]:
f.shape

torch.Size([1, 1, 150])

In [71]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [72]:
f_temp = f.squeeze(0)

In [73]:
z(f_temp)

tensor([[-0.0444, -0.3081,  0.2276,  0.2116, -0.2478,  0.3138,  0.0639,  0.3617,
          0.1462,  0.1819,  0.4059,  0.2505,  0.0437,  0.0041, -0.2253,  0.2105,
         -0.0475,  0.2737,  0.1887, -0.1475,  0.1960,  0.0933, -0.0140,  0.1727,
         -0.0364,  0.0415,  0.1658, -0.1263, -0.0425, -0.2048,  0.2613, -0.0191,
         -0.1091, -0.2792,  0.2588, -0.3589,  0.0100,  0.0080,  0.0184,  0.0587,
          0.1312,  0.1784,  0.1329,  0.0181, -0.2591,  0.2046,  0.2294, -0.1174,
         -0.1279, -0.6026,  0.1112, -0.0741, -0.2897, -0.1968, -0.0767,  0.0582,
          0.2084,  0.0969,  0.6127, -0.2615, -0.0965, -0.4594, -0.2088,  0.2837,
          0.2054, -0.2259,  0.2323,  0.0083,  0.4872, -0.3179,  0.4829,  0.3221,
          0.1766, -0.3024,  0.2109,  0.2784,  0.0680, -0.1211,  0.0697,  0.3457,
         -0.2696,  0.0983,  0.1167, -0.2499,  0.3297,  0.3676,  0.4149,  0.2681,
         -0.4686,  0.0064,  0.2419,  0.2944,  0.0226, -0.2702,  0.0401,  0.2360,
         -0.0867,  0.0131, -

In [74]:
len(f_temp[0])

150

In [75]:
len(z(f_temp)[0])

284

In [76]:
len(vocab)

284

In [77]:
for batch_x , batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,  11],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   6,  33,  34,  35,  36,   1,  37,  38],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
           1,   3,  79,  80,  81,  10,   1,  82,  64,  42],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  11, 116],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          11,  50, 153, 170, 232, 148, 233,  10, 234,  10],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   5,   6,   7,   8,   9,  10,  11,  12],
        [  0,   0,   0,   0

# Training loop

In [78]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 101.3989
Epoch: 2, Loss: 95.0012
Epoch: 3, Loss: 87.7585
Epoch: 4, Loss: 82.4384
Epoch: 5, Loss: 76.8513
Epoch: 6, Loss: 71.4149
Epoch: 7, Loss: 66.0974
Epoch: 8, Loss: 60.5879
Epoch: 9, Loss: 55.7172
Epoch: 10, Loss: 50.3781
Epoch: 11, Loss: 45.6990
Epoch: 12, Loss: 41.2029
Epoch: 13, Loss: 36.6813
Epoch: 14, Loss: 32.5507
Epoch: 15, Loss: 28.9698
Epoch: 16, Loss: 25.7920
Epoch: 17, Loss: 23.1888
Epoch: 18, Loss: 20.2693
Epoch: 19, Loss: 18.2730
Epoch: 20, Loss: 16.4252
Epoch: 21, Loss: 14.3456
Epoch: 22, Loss: 13.1418
Epoch: 23, Loss: 11.7114
Epoch: 24, Loss: 10.4602
Epoch: 25, Loss: 9.5688
Epoch: 26, Loss: 8.7343
Epoch: 27, Loss: 7.9587
Epoch: 28, Loss: 7.5014
Epoch: 29, Loss: 6.7845
Epoch: 30, Loss: 6.2940
Epoch: 31, Loss: 5.9093
Epoch: 32, Loss: 5.5643
Epoch: 33, Loss: 5.4506
Epoch: 34, Loss: 4.8901
Epoch: 35, Loss: 4.8035
Epoch: 36, Loss: 4.5682
Epoch: 37, Loss: 4.2118
Epoch: 38, Loss: 4.1719
Epoch: 39, Loss: 3.9752
Epoch: 40, Loss: 3.7511
Epoch: 41, Loss: 3.4995


# Prediction

In [79]:
max(len_list)

25

In [83]:
#logic
# [0]* (25-len(numerical_text)) + numerical_text

In [82]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]





In [84]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was nearly'

In [85]:
len(vocab)

284

In [86]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

# Generate Automatically

In [87]:
import time
num_tokens = 20
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

# Accuracy calculation

In [88]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy






In [89]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.76%
